const GET_POST_LIST="GET_POST_LIST";
const POST_STATUS="POST_STATUS";
const GET_POST_LIST_SEARCH = "GET_POST_LIST_SEARCH";
const GET_POST_LIST_PAGE = "GET_POST_LIST_PAGE";
const SET_VALUE_SEARCH = "SET_VALUE_SEARCH";
const GET_USER = "GET_USER";
const SET_MY_POST = "SET_MY_POST";
const UPDATE_MY_POST = "UPDATE_MY_POST";

const ActionType = {
    GET_POST_LIST,
    POST_STATUS,
    GET_POST_LIST_SEARCH,
    SET_VALUE_SEARCH,
    GET_POST_LIST_PAGE,
    GET_USER,
    SET_MY_POST,
    UPDATE_MY_POST
}

export default ActionType;